steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/argocd-clouddeploy-repo/argocd-clouddeploy-app:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/argocd-clouddeploy-repo/argocd-clouddeploy-app:$SHORT_SHA'
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$SHORT_SHA" > image_tag.txt
        ls -al
        cat image_tag.txt
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone git@github.com:${_GITHUB_REPO_OWNER}/${_GITHUB_REPO_NAME}.git argocd-gitops-manifests
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd argocd-gitops-manifests/base
        sed -i "s|us-central1-docker.pkg.dev/[^/]*/argocd-clouddeploy-repo/argocd-clouddeploy-app:[^ ]*|us-central1-docker.pkg.dev/$PROJECT_ID/argocd-clouddeploy-repo/argocd-clouddeploy-app:$(cat ../../image_tag.txt)|g" deployment.yaml
        cat deployment.yaml
  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-C'
      - 'argocd-gitops-manifests'
      - config
      - user.email
      - 'cloudbuild@example.com'
  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-C'
      - 'argocd-gitops-manifests'
      - config
      - user.name
      - 'Cloud Build'
  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-C'
      - 'argocd-gitops-manifests'
      - add
      - '.'
  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-C'
      - 'argocd-gitops-manifests'
      - commit
      - '-m'
      - 'Update image tag to $SHORT_SHA'
  - name: 'gcr.io/cloud-builders/git'
    args:
      - '-C'
      - 'argocd-gitops-manifests'
      - push
      - origin
      - 'HEAD:main'

substitutions:
  _GITHUB_REPO_OWNER: 'ss4aman' # replace with your github repo owner
  _GITHUB_REPO_NAME: 'argocd-gitops-manifests' # replace with your github repo name
